CREATE TABLE articles (
    id VARCHAR2(4000) PRIMARY KEY,
    publish_date DATE NOT NULL, page NUMBER NOT NULL,
    author VARCHAR2(255) NOT NULL, title VARCHAR2(255) NOT NULL,
    subject VARCHAR2(255) NOT NULL,
    paper_name  VARCHAR2(255) NOT NULL,
    file_path VARCHAR2(512) NOT NULL,
    word_num NUMBER NOT NULL
);


CREATE TABLE indices (
    article_id VARCHAR2(4000) NOT NULL,
    term VARCHAR2(255) NOT NULL,
    line NUMBER NOT NULL,
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paragraph NUMBER NOT NULL,
    type VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_article_id FOREIGN KEY (article_id) REFERENCES articles(id)
);


CREATE TABLE phrases (
    phrase VARCHAR2(255) NOT NULL PRIMARY KEY,
    definition VARCHAR2(255)
);

CREATE TABLE groups (
    name VARCHAR2(255) NOT NULL,
    word VARCHAR2(255) NOT NULL
);

ALTER TABLE groups add CONSTRAINT groups_unique UNIQUE (name, word);
